[project]
name = "rojo-showcase-template"

[paths]
src = "src"
darklua_build = "darklua_build"

[display]
file_changes = true
docs_enabled = false
logs_enabled = true
check_updates = true

[aliases]
Client = "src/client/"
Packages = "roblox_packages/"
Server = "src/server/"
ServerPackages = "roblox_server_packages/"
Shared = "src/shared/"
